### ISSUE TITLE
Working but dies after 5 minutes

### ISSUE THREAD

**Issue by moltenkaizen** [travelping/journal-gateway-gelf#5]
Using:
`env JOURNAL_GELF_REMOTE_TARGET=http://127.0.0.1:1234 JOURNAL_GELF_SOURCE_DIR=/var/log/journal ./journal-gateway-gelf`

Error after 5 minutes:

```
journal-gateway-gelf: ./src/journal-gateway-gelf.c:290: get_entry_string: Assertion `rc == 0' failed.
Aborted
```

**Comment by thz** [comment]
how is the RAM usage during the 5 minutes? the respective assertion is catching a failing memory allocation.

**Comment by moltenkaizen** [comment]
I didn't previously checked cpu/mem resources. When I saw 78% on the cpu of a production server, I had to kill the process. Perhaps memory usage would climb but with that cpu load, I'd need to setup a test server rather than putting the load on a production server.

```
PID USER      PR  NI    VIRT    RES    SHR S   %CPU  %MEM     TIME+ COMMAND
29805 root      20   0 6121332 191704 165060 R 78.947 0.290   0:14.45 journal-gateway
```

**Comment by mgumz** [comment]
@moltenkaizen how many log-messages are created on the production system per second/minute etc? how big is the "backlog" the forwarder has to process to catch up with whats thrown on top of it (how big is the journal-folder)?
